feat: setup testable pipelines

diff --git a/.github/workflows/pipeline-dev-tag.yml b/.github/workflows/pipeline-dev-tag.yml
--- a/.github/workflows/pipeline-dev-tag.yml
+++ b/.github/workflows/pipeline-dev-tag.yml
@@ -1,5 +1,4 @@
-name: "Release Pipeline"
-# TODO: Set workflow concurrency to 1 based on the input
+name: "Dev Tag Pipeline"
 
 on:
   workflow_dispatch:
@@ -13,134 +12,191 @@ permissions:
   contents: write
 
 jobs:
-  # TODO: Convert to re-usable action
   setup:
     runs-on: ubuntu-latest
+
+    outputs:
+      constantsVersion: ${{ steps.versions.outputs.constantsVersion }}
+      constantsVersionXy: ${{ steps.versions.outputs.constantsVersionXy }}
+      setupVersion: ${{ steps.versions.outputs.setupVersion }}
+      setupVersionXy: ${{ steps.versions.outputs.setupVersionXy }}
+      newestVersion: ${{ steps.versions.outputs.newestVersion }}
+      targetBranch: ${{ steps.versions.outputs.targetBranch }}
+      devTag: ${{ steps.versions.outputs.devTag }}
+      releaseTag: ${{ steps.versions.outputs.releaseTag }}
+
 
     steps:
       - uses: actions/checkout@v4
         with:
           ref: ${{ inputs.branch }}
           fetch-tags: true
+          # token: ${{ secrets.repo_PAT }}
 
       - name: Check if branch needs master merge
         run: |
+          git fetch origin master --depth 1
+
           if [[ $(git log origin/master ^HEAD) ]]; then
             echo "You need to merge master into this branch."
             exit 1
           fi
 
+      - name: Populate variables
+        id: versions
+        run: |
+          . ./hooks/populate-hook-constants.sh
+
+          echo "constantsVersion=$constantsVersion" | tee -a "$GITHUB_OUTPUT" "$GITHUB_ENV"
+          echo "constantsVersionXy=$constantsVersionXy" | tee -a "$GITHUB_OUTPUT" "$GITHUB_ENV"
+          echo "setupVersion=$setupVersion" | tee -a "$GITHUB_OUTPUT" "$GITHUB_ENV"
+          echo "setupVersionXy=$setupVersionXy" | tee -a "$GITHUB_OUTPUT" "$GITHUB_ENV"
+          echo "newestVersion=$newestVersion" | tee -a "$GITHUB_OUTPUT" "$GITHUB_ENV"
+          echo "targetBranch=$targetBranch" | tee -a "$GITHUB_OUTPUT" "$GITHUB_ENV"
+
+          echo "devTag=dev-v$setupVersion" | tee -a "$GITHUB_OUTPUT" "$GITHUB_ENV"
+          echo "releaseTag=v$setupVersion" | tee -a "$GITHUB_OUTPUT" "$GITHUB_ENV"
+
       - name: Check tag and branch correctness
         run: |
-          ./hooks/populate-hook-constants.sh
-
-          if ! [[ $setupVersion == ${{ inputs.branch }}* ]]
+          if [[ "${{ steps.versions.outputs.setupVersion }}" != ${{ inputs.branch }}* ]]
           then
             echo "Adding tag to wrong branch"
             exit 1
           fi
 
-          if git rev-parse v$setupVersion >/dev/null 2>&1
+          if git rev-parse ${{ steps.versions.outputs.releaseTag }} >/dev/null 2>&1
           then
               echo "The released version of this tag already exists."
               exit 1
           fi
 
       - name: Delete tag if already tagged
-        # TODO: Allow a way to force-update the tag in the workflow
-        # TODO: How do we want to get the commit hash?
         run: |
-          if ! [[ `git tag -l --points-at ${{ github.sha }}` == "" ]]
-          then
-            git tag --delete <tagName>
-            git push --delete origin <tagName>
-          fi
-
-      # TODO: I want to move the docs to the release script, instead of the dev script
+          git tag --delete ${{ steps.versions.outputs.devTag }} || true
+          git push --delete origin ${{ steps.versions.outputs.devTag }} || true
 
       - name: Create and push tag
-      # TODO: Use github script action
-      # TODO: Get a github token added
         run: |
-          ./hooks/populate-hook-constants.sh
+          # NOTE: The user email is {user.id}+{user.login}@users.noreply.github.com.
+          # See users API: https://api.github.com/users/github-actions%5Bbot%5D
+          git config user.name "github-actions[bot]"
+          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
 
-          git config user.name github-actions
-          git config user.email github-actions@github.com
+          git tag ${{ steps.versions.outputs.devTag }}
+          git push --tags --follow-tags
 
-          git tag dev-v$setupVersion ${{ github.sha }}
-          git push --tags
 
+  lint-code:
+    needs:
+      - setup
+
+    uses: ./.github/workflows/unit-test.yml
+    with:
+      ref: ${{ needs.setup.outputs.devTag }}
 
   mark-dev-tag-as-not-passed:
     runs-on: ubuntu-latest
     needs:
       - setup
+      - lint-code
 
     steps:
+      - uses: actions/checkout@v4
+        with:
+          ref: ${{ needs.setup.outputs.devTag }}
+          fetch-tags: true
+
       - id: versions
         uses: supertokens/get-supported-versions-action@main
         with:
           has-cdi: true
           has-fdi: true
 
-      - run: |
-          ./hooks/populate-hook-constants.sh
+      # - run: |
+      #     ./hooks/populate-hook-constants.sh
 
-          curl --fail-with-body -X PUT \
-              https://api.supertokens.io/0/driver \
-              -H 'Content-Type: application/json' \
-              -H 'api-version: 0' \
-              -d "{
-                \"password\": \"${{ secrets.SUPERTOKENS_API_KEY }}\",
-                \"version\":\"$setupVersion\",
-                \"name\": \"python\",
-                \"frontendDriverInterfaces\": ${{ steps.versions.outputs.fdiVersions }},
-                \"coreDriverInterfaces\": ${{ steps.versions.outputs.cdiVersions }}
-              }"`
+      #     curl --fail-with-body -X PUT \
+      #         https://api.supertokens.io/0/driver \
+      #         -H 'Content-Type: application/json' \
+      #         -H 'api-version: 0' \
+      #         -d "{
+      #           \"password\": \"${{ secrets.SUPERTOKENS_API_KEY }}\",
+      #           \"version\":\"$${{ needs.setup.outputs.setupVersion }}\",
+      #           \"name\": \"python\",
+      #           \"frontendDriverInterfaces\": ${{ steps.versions.outputs.fdiVersions }},
+      #           \"coreDriverInterfaces\": ${{ steps.versions.outputs.cdiVersions }}
+      #         }"`
 
-  unit-test:
-    needs: mark-dev-tag-as-not-passed
-    uses: ./.github/workflows/unit-test.yml
+  # unit-test:
+  #   needs:
+  #     - setup
+  #     - mark-dev-tag-as-not-passed
+  #   uses: ./.github/workflows/unit-test.yml
+  #   with:
+  #     ref: ${{ needs.setup.outputs.devTag }}
 
-  backend-sdk-test:
-    needs: mark-dev-tag-as-not-passed
-    uses: ./.github/workflows/backend-sdk-testing.yml
+  # backend-sdk-test:
+  #   needs:
+  #     - setu
+  #     - mark-dev-tag-as-not-passed
+  #   uses: ./.github/workflows/backend-sdk-testing.yml
+  #   with:
+  #     ref: ${{ needs.setup.outputs.devTag }}
 
-  website-test:
-    needs: mark-dev-tag-as-not-passed
-    uses: ./.github/workflows/website-test.yml
+  # website-test:
+  #   needs:
+  #     - setup
+  #     - mark-dev-tag-as-not-passed
+  #   uses: ./.github/workflows/website-test.yml
+  #   with:
+  #     ref: ${{ needs.setup.outputs.devTag }}
 
-  auth-react-test:
-    needs: mark-dev-tag-as-not-passed
-    strategy:
-      matrix:
-        framework:
-          - django
-          - fastapi
-          - flask
+  # auth-react-test-django:
+  #   needs:
+  #     - setup
+  #     - mark-dev-tag-as-not-passed
+  #   uses: ./.github/workflows/auth-react-test-1-django.yml
+  #   with:
+  #     ref: ${{ needs.setup.outputs.devTag }}
 
-    uses: ./.github/workflows/auth-react-test-1-${{ matrix.framework }}.yml
+  # auth-react-test-fastapi:
+  #   needs:
+  #     - setup
+  #     - mark-dev-tag-as-not-passed
+  #   uses: ./.github/workflows/auth-react-test-1-fastapi.yml
+  #   with:
+  #     ref: ${{ needs.setup.outputs.devTag }}
 
-  mark-as-success:
-    runs-on: ubuntu-latest
+  # auth-react-test-flask:
+  #   needs:
+  #     - setup
+  #     - mark-dev-tag-as-not-passed
+  #   uses: ./.github/workflows/auth-react-test-1-flask.yml
+  #   with:
+  #     ref: ${{ needs.setup.outputs.devTag }}
 
-    needs:
-      - unit-test
-      - backend-sdk-test
-      - website-test
-      - auth-react-test
+  # mark-as-success:
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - run: |
-          ./hooks/populate-hook-constants.sh
+  #   needs:
+  #     - unit-test
+  #     - backend-sdk-test
+  #     - website-test
+  #     - auth-react-test-django
+  #     - auth-react-test-fastapi
+  #     - auth-react-test-flask
 
-          curl --fail-with-body -X PATCH \
-              https://api.supertokens.io/0/driver \
-              -H 'Content-Type: application/json' \
-              -H 'api-version: 0' \
-              -d "{
-                \"password\": \"${{ secrets.SUPERTOKENS_API_KEY }}\",
-                \"version\":\"$setupVersion\",
-                \"name\": \"python\",
-                \"testPassed\": true
-              }"`
+  #   steps:
+  #     - run: echo "Yay"
+  #     # - run: |
+  #     #     curl --fail-with-body -X PATCH \
+  #     #         https://api.supertokens.io/0/driver \
+  #     #         -H 'Content-Type: application/json' \
+  #     #         -H 'api-version: 0' \
+  #     #         -d "{
+  #     #           \"password\": \"${{ secrets.SUPERTOKENS_API_KEY }}\",
+  #     #           \"version\":\"${{ needs.setup.outputs.setupVersion }}\",
+  #     #           \"name\": \"python\",
+  #     #           \"testPassed\": true
+  #     #         }"`
